title: Majin Evelyn TTRPG Blog
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

# color_scheme: dark
color_scheme: darkOverride

search_enabled: true

url: https://majinevelyn.com/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
