title: Majin Evelyn TTRPG Blog
description: A tactics and character building blog focused on TTRPGs.
theme: just-the-docs

# color_scheme: dark
color_scheme: darkOverride

search_enabled: true

url: https://majinevelyn.com/

aux_links:
  Tabletop Builds: https://tabletopbuilds.com/
